# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Constructed Intellect
email: ''
description: > # this means to ignore newlines until "baseurl:"
  A blog and podcast covering the business and technology of artificial intelligence.
copyright: © 2015-2016 Ray Grieselhuber
baseurl: "/constructed-intellect" # the subpath of your site, e.g. /blog
url: "http://www.constructedintellect.com" # the base hostname & protocol for your site
twitter_username: conintellect
github_username:  rgrieselhuber

# Build settings
markdown: kramdown
logo_path: "logo.png"